import type { Env } from '../../../_shared';
import { jsonRes, preflight, siteOrigin } from '../_shared';
import {
  BUNDLE_WRITER_ROLES,
  fetchChainSegment,
  memberEmail,
  requireEvidenceAccess,
  seqRangeForPeriod,
  signingKeyFor,
  type EvidenceAccess,
} from './_shared';
import { verifyChain } from '../../../../src/services/auditChain';
import { appendAuditEvent, type AuditActorRole } from '../../../../src/services/auditChain';
import {
  MAX_BUNDLE_EVENTS,
  buildEventsJsonl,
  computeBundleHash,
  countsByTypeOf,
  keyFingerprint,
  sha256HexOf,
  signBundle,
} from '../../../../src/services/evidenceBundle';

// Sprint 9 (compliance tier) — POST /api/teams/evidence/bundle
//
// Generates a signed evidence bundle for a reporting period. Nothing is
// stored but the manifest row: the chain is immutable, so the archive is
// regenerated byte-for-byte on every download (and re-verified as it is).
//
// Order matters: verify the segment → hash → sign → INSERT the immutable row
// (id + created_at generated here so the signature can bind to them) → chain
// event. A broken segment is refused: you do not get to sign a broken chain.

const MAX_PERIOD_DAYS = 366;

export interface BundleCreateDeps {
  access(request: Request): Promise<EvidenceAccess | Response>;
  now?: () => Date;
  newId?: () => string;
  siteUrl?: string;
}

interface Body {
  period_from?: unknown;
  period_to?: unknown;
}

function isoDate(v: unknown): string | null {
  if (typeof v !== 'string') return null;
  const t = Date.parse(v);
  return Number.isNaN(t) ? null : new Date(t).toISOString();
}

export async function handleBundleCreate(request: Request, deps: BundleCreateDeps): Promise<Response> {
  if (request.method !== 'POST') return jsonRes({ error: 'Method not allowed' }, 405);
  const access = await deps.access(request);
  if (access instanceof Response) return access;
  const { db, team, role, clerkUserId } = access;
  if (!BUNDLE_WRITER_ROLES.has(role)) return jsonRes({ error: 'Only an owner, manager or auditor can generate evidence bundles' }, 403);

  let body: Body;
  try {
    body = (await request.json()) as Body;
  } catch {
    return jsonRes({ error: 'Invalid JSON body' }, 400);
  }
  const from = isoDate(body.period_from);
  const to = isoDate(body.period_to);
  if (!from || !to) return jsonRes({ error: 'period_from and period_to must be ISO-8601 timestamps' }, 400);
  if (to < from) return jsonRes({ error: 'period_to must be >= period_from' }, 400);
  if ((Date.parse(to) - Date.parse(from)) / 86_400_000 > MAX_PERIOD_DAYS) {
    return jsonRes({ error: `period must be ${MAX_PERIOD_DAYS} days or fewer` }, 400);
  }

  // 1. Segment for the period.
  const range = await seqRangeForPeriod(db, team.id, from, to);
  if (!range) return jsonRes({ error: 'No chain events in that period — nothing to bundle' }, 409);
  if (range.toSeq - range.fromSeq + 1 > MAX_BUNDLE_EVENTS) {
    return jsonRes({ error: `Period covers more than ${MAX_BUNDLE_EVENTS} events — narrow it` }, 413);
  }
  let rows;
  try {
    rows = await fetchChainSegment(db, team.id, range.fromSeq, range.toSeq);
  } catch (e) {
    return jsonRes({ error: (e as Error).message }, 500);
  }

  // 2. Refuse to sign a broken chain.
  const chain = await verifyChain(rows);
  if (!chain.ok) return jsonRes({ error: 'Chain segment does not verify — not signing it', chain }, 409);
  const head = rows[rows.length - 1];

  // 3. Content hash.
  const eventsJsonl = buildEventsJsonl(rows);
  const bundleHash = await computeBundleHash(eventsJsonl, { teamId: team.id, fromSeq: range.fromSeq, toSeq: range.toSeq, headHash: head.hash });

  // 4. Sign with the active key, bound to this row's id + created_at.
  const key = await signingKeyFor(db, team.id);
  if (!key) return jsonRes({ error: 'Team has no active signing key' }, 500);
  const createdAt = (deps.now?.() ?? new Date()).toISOString();
  const bundleId = deps.newId?.() ?? crypto.randomUUID();
  const signature = await signBundle(key.key_hex, bundleHash, bundleId, createdAt);
  const counts = countsByTypeOf(rows);

  // 5. The immutable manifest row — one INSERT, no later UPDATE possible.
  const { error: insErr } = await db.from('evidence_bundles').insert({
    id: bundleId,
    team_id: team.id,
    period_from: from,
    period_to: to,
    chain_from_seq: range.fromSeq,
    chain_to_seq: range.toSeq,
    chain_head_hash: head.hash,
    event_count: rows.length,
    validation_count: counts.validation_run,
    approval_count: counts.approval_requested + counts.approval_approved + counts.approval_rejected,
    bundle_hash: bundleHash,
    signature,
    signing_key_version: key.version,
    generated_by: clerkUserId,
    generated_by_role: role,
    format_version: 1,
    created_at: createdAt,
  });
  if (insErr) return jsonRes({ error: `Could not record bundle: ${insErr.message}` }, 500);

  // 6. Chain: the bundle's existence is itself evidence.
  let seq: number | null = null;
  try {
    seq = await appendAuditEvent(db, {
      teamId: team.id,
      eventType: 'evidence_bundle_generated',
      actor: clerkUserId,
      actorRole: role as AuditActorRole,
      subject: bundleId,
      payload: {
        bundle_id: bundleId,
        period: { from, to },
        chain: { from_seq: range.fromSeq, to_seq: range.toSeq, head_hash: head.hash, event_count: rows.length },
        bundle_hash: bundleHash,
        key_version: key.version,
        key_fingerprint: await keyFingerprint(key.key_hex),
      },
    });
  } catch (e) {
    console.warn('evidence_bundle_generated chain event not recorded', (e as Error).message);
  }

  const base = deps.siteUrl ?? '';
  return jsonRes(
    {
      bundle: {
        id: bundleId,
        team_id: team.id,
        period_from: from,
        period_to: to,
        chain_from_seq: range.fromSeq,
        chain_to_seq: range.toSeq,
        chain_head_hash: head.hash,
        event_count: rows.length,
        validation_count: counts.validation_run,
        approval_count: counts.approval_requested + counts.approval_approved + counts.approval_rejected,
        bundle_hash: bundleHash,
        signature,
        signing_key_version: key.version,
        generated_by: clerkUserId,
        generated_by_role: role,
        generated_by_email: await memberEmail(db, team.id, clerkUserId),
        format_version: 1,
        created_at: createdAt,
      },
      chain,
      events_sha256: await sha256HexOf(eventsJsonl),
      event_seq: seq,
      download_url: `${base}/api/teams/evidence/bundle/${bundleId}/download`,
      verify_url: `${base}/api/teams/evidence/bundle/${bundleId}/verify`,
    },
    201,
  );
}

export const onRequestOptions = preflight;

export const onRequestPost = async (context: { request: Request; env: Env }): Promise<Response> =>
  handleBundleCreate(context.request, {
    access: (req) => requireEvidenceAccess(req, context.env),
    siteUrl: siteOrigin(context.env),
  });
