import { LegalShell, LegalSection, P, UL } from '../components/LegalShell';

// /security — Security page. Static content page.
export function SecurityPage() {
  return (
    <LegalShell
      title="Security at SafeSQL Pro"
      subtitle="How we protect your queries, schemas, and credentials."
    >
      <LegalSection title="1 — Infrastructure">
        <P>
          SafeSQL Pro runs on Cloudflare Pages and Workers — one of the most secure and resilient
          infrastructure platforms available. Your validation requests are processed at the edge, close
          to you, with no data crossing unnecessary network hops.
        </P>
        <P>
          Database: Supabase (PostgreSQL on AWS) with row-level security enforced on every table. No
          query can access another user's data at the database level.
        </P>
      </LegalSection>

      <LegalSection title="2 — Credential security">
        <P>Database connection strings (Schema Connector feature) are protected by multiple layers:</P>
        <UL
          items={[
            'AES-256-GCM encryption before storage',
            'Encryption key stored in Cloudflare Workers secrets — separate from the encrypted data, never in the database',
            'Decryption happens only inside the Cloudflare Worker at request time — credentials are never decrypted client-side or logged',
            'Connection strings are used only for INFORMATION_SCHEMA introspection — we never read table contents',
          ]}
        />
      </LegalSection>

      <LegalSection title="3 — API key security">
        <P>
          API keys are stored as SHA-256 hashes only. The plaintext key is shown once at generation — we
          cannot recover it. If a key is lost, generate a new one and revoke the old one.
        </P>
      </LegalSection>

      <LegalSection title="4 — SQL query handling">
        <P>Your SQL queries are processed by our validation engine to detect semantic errors. We do not:</P>
        <UL
          items={[
            'Store the raw SQL text of your queries in plaintext beyond what is needed for your validation history',
            'Use your queries to train AI models',
            'Share your queries or schemas with third parties',
            'Index or search the content of your queries',
          ]}
        />
        <P>
          AI explanations (Pro tier) are generated by Anthropic's Claude API. Only the detected issue +
          minimal context is sent — not your full query or schema. Anthropic's data usage policy applies
          to this processing.
        </P>
      </LegalSection>

      <LegalSection title="5 — Authentication">
        <P>Authentication is handled by Clerk with support for:</P>
        <UL
          items={[
            'Google OAuth 2.0',
            'Email + password (bcrypt hashed by Clerk)',
            'Magic link email login',
          ]}
        />
        <P>We never store passwords. Session tokens are short-lived and rotated automatically.</P>
      </LegalSection>

      <LegalSection title="6 — Transport security">
        <P>
          All traffic to safesqlpro.dev is served over TLS 1.3 with HSTS enabled. The .dev TLD enforces
          HTTPS at the registry level — HTTP connections are rejected.
        </P>
      </LegalSection>

      <LegalSection title="7 — Data isolation">
        <P>Every database table uses Supabase Row Level Security (RLS). Policies ensure:</P>
        <UL
          items={[
            'Users can only access their own validation history',
            "Team members can only access their team's data",
            'API keys can only access data belonging to their owner',
            'Shared validations are intentionally public but contain no personally identifiable information',
          ]}
        />
      </LegalSection>

      <LegalSection title="8 — Responsible disclosure">
        <P>
          If you discover a security vulnerability in SafeSQL Pro, please report it to
          security@safesqlpro.dev.
        </P>
        <P>Please:</P>
        <UL
          items={[
            'Give us reasonable time to investigate (we aim for 72hr)',
            "Avoid accessing or modifying other users' data",
            'Do not publicly disclose the vulnerability before we have had a chance to address it',
          ]}
        />
        <P>
          We do not currently offer a bug bounty program, but we will acknowledge your contribution and
          notify you when the issue is resolved.
        </P>
      </LegalSection>

      <LegalSection title="9 — Incident response">
        <P>In the event of a confirmed data breach:</P>
        <UL
          items={[
            'We will notify affected users within 72 hours',
            'We will notify relevant supervisory authorities as required by GDPR and applicable law',
            'We will publish a post-incident report within 30 days',
          ]}
        />
      </LegalSection>

      <LegalSection title="10 — SOC 2 alignment">
        <P>SafeSQL Pro's security controls are designed to align with SOC 2 Type 1 Trust Service Criteria:</P>
        <UL
          items={[
            'Security: encryption, access controls, audit logging',
            'Availability: Cloudflare global infrastructure',
            'Confidentiality: schema credentials never stored in plaintext',
            'Processing integrity: deterministic rule engine, no AI hallucinations in detection decisions',
            'Privacy: data minimization, retention limits, GDPR rights',
          ]}
        />
        <P>
          We are working toward a formal SOC 2 Type 1 audit. Our audit log is available to Business and
          Enterprise tier customers at{' '}
          <a href="#/team/audit" style={{ color: '#a78bfa' }}>safesqlpro.dev/team/audit</a>.
        </P>
        <P>Contact: security@safesqlpro.dev</P>
      </LegalSection>
    </LegalShell>
  );
}
